### ISSUE TITLE
run_all script fails after Mac OS X 10.15 Catalina Update

### ISSUE THREAD

**Issue by stefanalex99** [malus-security/iExtractor#10]
Following the OS X 10.15 Catalina update, run_all script fails creating /mnt directory because the "root" directory is read-only. A quick fix is to create a root level symbolic link by creating and editing the /etc/synthetic.conf. [1]

[1] https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/

**Comment by razvand** [comment]
The proper solution to this is not the use the top-level `/mnt/` directory. The most direct way is the define a `MOUNT_DIR` variable in the [config file](https://github.com/malus-security/iextractor/blob/master/config.sample) and initialize it `"$STORE"/mnt`.

@stefanalex99 , do this ^ , test it to see if it works and then submit a pull request. When submitting the pull request, reference this issue (#10).
